# Service principal can be the same SPN as the client or a dedicated one issued in the same
# Kerberos realm
server:
    port: 8081
app:
    service-principal: SERV/service.domain.com@domain.com
    keytab-location: /tmp/service.keytab
